# Generated by Django 2.2.2 on 2019-07-01 11:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 11, 17, 23, 409458), null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 11, 17, 23, 409478), null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 11, 17, 23, 408260), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 11, 17, 23, 410186), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 11, 17, 23, 410206), null=True),
        ),
    ]
