# Generated by Django 2.2.2 on 2019-06-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0002_auto_20190625_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
