# Generated by Django 2.2.2 on 2019-06-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0003_auto_20190625_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
