# Generated by Django 2.2.2 on 2019-07-01 11:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0003_auto_20190701_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 11, 19, 11, 818113), null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 11, 19, 11, 818134), null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 11, 19, 11, 816911), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 11, 19, 11, 818867), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 11, 19, 11, 818888), null=True),
        ),
    ]
