# Generated by Django 2.2.2 on 2019-06-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0004_auto_20190625_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
