# Generated by Django 2.2.2 on 2019-07-01 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0014_auto_20190701_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 25, 18, 477611), null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 25, 18, 477635), null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 25, 18, 476347), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 25, 18, 478332), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 25, 18, 478353), null=True),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 25, 18, 475793)),
        ),
    ]
