# Generated by Django 2.2.2 on 2019-07-01 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquora', '0018_auto_20190701_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 33, 36, 968367), null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 33, 36, 968393), null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 33, 36, 966406), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 33, 36, 969058), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 33, 36, 969080), null=True),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 7, 1, 9, 33, 36, 967050)),
        ),
    ]
